apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      application: edge-service
  template:
    metadata:
      labels:
        application: edge-service
    spec:
      containers:
      - name: edge-service
        image: quay.io/ted_ross/skupper-edge-service
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/messaging/
          name: connect
      volumes:
      - name: connect
        secret:
          secretName: skupper
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service-rdu0
  labels:
    app: edge-service
    service: edge-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: edge-service
